### ISSUE TITLE
V3 Roadmap

### ISSUE THREAD

**Issue by collinc777** [hoangvvo/next-session#69]
Is there a V3 roadmap out there? I'd love to help push this along to the next version.

**Comment by hoangvvo** [comment]
Thanks for your interest :fire: I'm having trouble in #71 if you would like to take a look.

Beside that, in my mind are:
- add `decode`/`encode` function to "encrypt" (prevent tamper cookie/not actually encrypt) sessionId
- not requiring session store to extend Store (as well as providing fallback for stores that do because of `express-session`)

Thanks a lot again!
